disabled_rules:
  - line_length
opt_in_rules:
  - empty_count
included:
  - FrameStepper
excluded:
  - Pods

force_cast: warning
force_try: warning
variable_name:
  min_length: 1
type_name:
  min_length: 1

